name: envio-indexer
disable_default_cross_chain: true
contracts:
  - name: YourContract
    handler: src/EventHandlers.ts
    events:
      - event: GreetingChange(address indexed greetingSetter, string newGreeting, bool premium, uint256 value)
chains:
  - id: 31337
    start_block: 1
    rpc: http://localhost:8545
    contracts:
      - name: YourContract
        address:
          - '0x5FbDB2315678afecb367f032d93F642f64180aa3'
